# Generated by Django 4.0.3 on 2022-06-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gymtrack_g_uid_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('isOpen', models.BooleanField(default=False)),
                ('acc_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_uid', to='core.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.CharField(max_length=20)),
                ('qrCode_id', models.IntegerField(default=0)),
                ('acc_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accc_uid', to='core.authuser')),
                ('q_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quid', to='core.queue')),
            ],
        ),
    ]
