# Generated by Django 4.0.3 on 2022-06-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_queue_queueuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='acc_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_authUser_uid', to='core.authuser'),
        ),
    ]
