# Generated by Django 4.0.3 on 2022-06-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_queue_acc_uid_alter_queueuser_q_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'ordering': ['id']},
        ),
    ]
