# Generated by Django 4.0.3 on 2022-06-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
