# Generated by Django 4.0.3 on 2022-06-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='queueuser',
            options={'ordering': ['id']},
        ),
    ]
