# Generated by Django 4.0.3 on 2022-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_queue_acc_uid_alter_queueuser_acc_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueuser',
            name='q_name',
            field=models.CharField(default='no value', max_length=80),
        ),
    ]
