# Generated by Django 4.0.3 on 2022-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_queueuser_q_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueuser',
            name='acc_name',
            field=models.CharField(default='no value', max_length=80),
        ),
    ]
